// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtoOSpjfnJqffoRGaEwg0aoOSRoWeiQ3A',
    appId: '1:855342784879:web:1a2fd3d3981a96bf37489a',
    messagingSenderId: '855342784879',
    projectId: 'lender-4bcef',
    authDomain: 'lender-4bcef.firebaseapp.com',
    storageBucket: 'lender-4bcef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASJZKdWUlUaAGleCYzS7jGcs8aFjvM_mo',
    appId: '1:855342784879:android:0579c13315de754a37489a',
    messagingSenderId: '855342784879',
    projectId: 'lender-4bcef',
    storageBucket: 'lender-4bcef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs6RVP6kiDEBm25O2A98WBQLiG4k-pSis',
    appId: '1:855342784879:ios:dd52f7d74454d32b37489a',
    messagingSenderId: '855342784879',
    projectId: 'lender-4bcef',
    storageBucket: 'lender-4bcef.firebasestorage.app',
    iosBundleId: 'com.example.lender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs6RVP6kiDEBm25O2A98WBQLiG4k-pSis',
    appId: '1:855342784879:ios:dd52f7d74454d32b37489a',
    messagingSenderId: '855342784879',
    projectId: 'lender-4bcef',
    storageBucket: 'lender-4bcef.firebasestorage.app',
    iosBundleId: 'com.example.lender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtoOSpjfnJqffoRGaEwg0aoOSRoWeiQ3A',
    appId: '1:855342784879:web:877dd25686c07db137489a',
    messagingSenderId: '855342784879',
    projectId: 'lender-4bcef',
    authDomain: 'lender-4bcef.firebaseapp.com',
    storageBucket: 'lender-4bcef.firebasestorage.app',
  );
}
